import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "csv-parse/sync";

const root = process.cwd();
const inputPath = path.join(root, "DB-Snapshot-CSV", "RealmSpark People Members.csv");
const dataDir = path.join(root, "app", "data");
const supabaseSeedPath = path.join(root, "supabase", "seed.sql");
const appSeedPath = path.join(dataDir, "members.seed.json");

const normalizeHeader = (value) => value.replace(/^\uFEFF/, "").trim();

const slugify = (value) =>
  value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 80);

const stableId = (name, email) => {
  const suffix = createHash("sha1").update(`${name}|${email || ""}`).digest("hex").slice(0, 10);
  return `snapshot-member-${slugify(name)}-${suffix}`;
};

const sqlString = (value) => {
  if (value === null || value === undefined || value === "") return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
};

const sqlArray = (values) => {
  if (!values.length) return "'{}'::text[]";
  return `array[${values.map(sqlString).join(", ")}]::text[]`;
};

const csv = await readFile(inputPath, "utf8");
const rows = parse(csv, {
  columns: (headers) => headers.map(normalizeHeader),
  skip_empty_lines: true,
  trim: true
});

const members = rows
  .filter((row) => row.Name?.trim())
  .map((row) => {
    const name = row.Name.trim();
    const email = row.Email?.trim() || null;
    const relatedOrganization = row["Related Organization"]?.trim() || null;
    const aliases = Array.from(
      new Set([
        name,
        ...name.split(/\s+/).filter((part) => part.length > 2),
        ...(relatedOrganization ? [relatedOrganization] : [])
      ])
    );

    return {
      airtable_id: stableId(name, email),
      name,
      aliases,
      related_organization: relatedOrganization,
      email,
      linkedin: row.LinkedIn?.trim() || null,
      raw_hash: createHash("sha256").update(JSON.stringify(row)).digest("hex")
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const seedSql = `-- Generated by npm run preseed:members.
-- Snapshot source: DB-Snapshot-CSV/RealmSpark People Members.csv

insert into members (
  airtable_id,
  name,
  aliases,
  related_organization,
  email,
  linkedin,
  raw_hash,
  material_change,
  status,
  synced_at
) values
${members
  .map(
    (member) => `  (
    ${sqlString(member.airtable_id)},
    ${sqlString(member.name)},
    ${sqlArray(member.aliases)},
    ${sqlString(member.related_organization)},
    ${sqlString(member.email)},
    ${sqlString(member.linkedin)},
    ${sqlString(member.raw_hash)},
    true,
    'active',
    now()
  )`
  )
  .join(",\n")}
on conflict (airtable_id) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  related_organization = excluded.related_organization,
  email = excluded.email,
  linkedin = excluded.linkedin,
  raw_hash = excluded.raw_hash,
  material_change = members.raw_hash is distinct from excluded.raw_hash,
  status = 'active',
  synced_at = now();
`;

await mkdir(dataDir, { recursive: true });
await mkdir(path.dirname(supabaseSeedPath), { recursive: true });
await writeFile(appSeedPath, `${JSON.stringify(members, null, 2)}\n`);
await writeFile(supabaseSeedPath, seedSql);

console.log(`Preseeded ${members.length} members`);
console.log(`Wrote ${path.relative(root, appSeedPath)}`);
console.log(`Wrote ${path.relative(root, supabaseSeedPath)}`);
